spring:
  profiles:
    active: dev

#---------------------------------------------------
logging:
  level:
  org.springframework.web: INFO
  Controller.Ch522Application: INFO

#----------------------------------------------------
debug: true
